services:
  contributor-app:
    build:
      context: ../../..
      dockerfile: ./deploy/contributor/production/Dockerfile
    container_name: contributor-app-prod
    ports:
      - "8082:8082"
      - "8093:8093"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8082/v1/health-check > /dev/null"]
      interval: 5s
      timeout: 3s
      retries: 12
    networks:
      - rankr-prod-network
    env_file:
      - ../../.env.production
    environment:
      - CONFIG_PATH=/app/deploy/contributor/production/config.yml
      - ENV=production
      - contributor_postgres_db__password=${CONTRIBUTOR_PASS}

networks:
  rankr-prod-network:
    external: true
    name: rankr-prod-network