services:
  task-app:
    build:
      context: ../../..
      dockerfile: ./deploy/task/production/Dockerfile
    container_name: task-app-prod
    networks:
      - rankr-prod-network
    env_file:
      - ../../.env.production
    environment:
      - CONFIG_PATH=/app/deploy/task/production/config.yml
      - ENV=production
      - task__postgres_db__password=${TASK_PASS}

networks:
  rankr-prod-network:
    external: true
    name: rankr-prod-network