services:
  realtime-app:
    build:
      context: ../../..
      dockerfile: ./deploy/realtime/production/Dockerfile
    container_name: realtime-app-prod
    ports:
      - "8087:8081"
      - "8097:8091"
    networks:
      - rankr-prod-network
    env_file:
      - ../../.env.production
    environment:
      - CONFIG_PATH=/app/deploy/realtime/production/config.yml
      - ENV=production
      - REALTIME_POSTGRES_DB__PASSWORD=${REALTIME_PASS}

networks:
  rankr-prod-network:
    external: true
    name: rankr-prod-network