services:
  notification-app:
    build:
      context: ../../..
      dockerfile: ./deploy/notification/production/Dockerfile
    container_name: notification-app-prod
    ports:
      - "8085:8081"
      - "8095:8091"
    networks:
      - rankr-prod-network
    env_file:
      - ../../.env.production
    environment:
      - CONFIG_PATH=/app/deploy/notification/production/config.yml
      - ENV=production
      - NOTIF__POSTGRES_DB__PASSWORD=${NOTIFAPP_PASS}

networks:
  rankr-prod-network:
    external: true
    name: rankr-prod-network