services:
  notification-app:
    build:
      context: ../../..
      dockerfile: ./deploy/notification/production/Dockerfile
    container_name: notification-app-prod
    ports:
      - "8089:8081"
      - "8099:8091"
    networks:
      - rankr-shared-development-network
    env_file:
      - ./.env.production
    environment:
      - CONFIG_PATH=/app/deploy/notification/production/config.yml
      - ENV=production

networks:
  rankr-shared-development-network:
    external: true
    name: rankr-shared-development-network