services:
  webhook-app:
    build:
      context: ../../..
      dockerfile: ./deploy/webhook/production/Dockerfile
    container_name: webhook-app-prod
    ports:
      - "8090:8090"
    networks:
      - rankr-prod-network
    env_file:
      - ../../.env.production
    environment:
      - CONFIG_PATH=/app/deploy/webhook/production/config.yml
      - ENV=production
      - WEBHOOK__POSTGRES_DB__PASSWORD=${WEBHOOK_PASS}

networks:
  rankr-prod-network:
    external: true
    name: rankr-prod-network