http_server:
  host: ""
  port: 8082
  shutdown_context_timeout: 10s

rpc_server:
  host: ""
  port: 8093
  network_type: "tcp"

redis:
  host: "localhost"
  port: 6380
  password: ""
  db: 0

logger:
  level: "debug"
  file_path: ""
  use_local_time: true
  file_max_size_in_mb: 10
  file_max_age_in_days: 7

total_shutdown_timeout: 30s

path_of_migration: "./contributorapp/repository/migrations"

postgres_db:
  host: localhost
  port: 5439
  user: contributor_user
  password: change_me_contributor
  db_name: contributor_db
  ssl_mode: disable
  max_conns: 5
  min_conns: 1
  max_conn_lifetime: 300
  max_conn_idle_time: 60
  health_check_period: 60