services:
  contributor-app:
    build:
      context: ../../.. # Build from the project root
      dockerfile: ./deploy/contributor/development/Dockerfile
    container_name: contributor-app
    volumes:
      - ../../..:/app
      - ./logs:/app/logs # Persist contributor logs
    ports:
      - "8082:8083" # HTTP port
      - "8093:8093" # gRPC port
    networks:
      - rankr-shared-development-network
    environment:
      - CONFIG_PATH=/app/deploy/contributor/development/config.yml
      - contributor_POSTGRES_DB_HOST=shared-postgres
      - contributor_REDIS_HOST=shared-redis
      - contributor_NATS_URL=nats://shared-nats:4222
    entrypoint: [ "air", "-c", "/app/.air/.air.contributor.toml" ]

networks:
  rankr-shared-development-network:
    external: true
