version: "3"
services:
  nginx:
    image: openresty/openresty:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./conf.d:/usr/local/openresty/nginx/conf/conf.d:ro
    networks:
      - rankr-shared-development-network
#    depends_on:
#      - postgres
#      - auth


networks:
  rankr-shared-development-network:
    name: rankr-shared-development-network
    external: true
