total_shutdown_timeout: "15s"
path_of_migration: "./leaderboardstatapp/repository/migrations"

http_server:
  host: ""
  port: 6011
  cors:
    allow_origins: "*"
  shutdown_context_timeout: "10s"

rpc_server:
  host: "0.0.0.0"
  port: 8090
  network_type: "tcp"

postgres_db:
  host: "rankr-shared-postgres"
  port: 5432
  user: "leaderboardstat_user"
  password: "leaderboard_pass_123"
  db_name: "leaderboardstat_db"
  ssl_mode: "disable"

  # pgx pool configs
  min_conns: 1
  max_conns: 20
  max_conn_lifetime: 300
  max_conn_idle_time: 60
  health_check_period: 30

logger:
  level: "debug"
  file_path: "logs/leaderboardstat/service.log"
  use_local_time: true
  file_max_size_in_mb: 10
  file_max_age_in_days: 7

leaderboard_scoring_rpc:
  host: "localhost"                   # Host where leaderboardscoring service runs
  port: 8090                          # Port from your leaderboardscoring gRPC server
  grpc_service_name: "leaderboardscoring.v1.LeaderboardScoringService"  # Service name from protobuf
  max_attempts: 3                     # Retry attempts
  initial_backoff: "1s"               # Initial backoff
  max_backoff: "5s"                   # Maximum backoff
  backoff_multiplier: 2.0             # Backoff multiplier
  retryable_status_codes:             # Status codes to retry
    - "UNAVAILABLE"
    - "RESOURCE_EXHAUSTED"
    - "INTERNAL"
  