services:
  leaderboardstat-service:
    build:
      context: .
      dockerfile: ./deploy/leaderboardstat/development/Dockerfile
    image: rankr-leaderboardstat:development
    command: /bin/leaderboardstat serve --migrate-up
    networks:
      - rankr-shared-development-network
    volumes:
      - ./:/home/app
    environment:
      - CONFIG_PATH=/home/app/deploy/leaderboardstat/development/config.yml
      - GRPC_NETWORK_TYPE=tcp
      - GRPC_PORT=8090
    ports:
      - "6011:6011"
      - "8098:8090"
    restart: unless-stopped

networks:
  rankr-shared-development-network:
    external: true

volumes:
  leaderboardstat-data:
