services:
  leaderboardstat-app:
    build:
      context: ../../.. # Build from the project root
      dockerfile: ./deploy/leaderboardstat/development/Dockerfile
    container_name: leaderboardstat-app
    volumes:
      - ../../..:/app
    ports:
      - "8088:8081" # HTTP port
      - "8098:8091" # gRPC port
    networks:
      - rankr-shared-development-network
    environment:
      - CONFIG_PATH=/app/deploy/leaderboardstat/development/config.yml
      - leaderboardstat_POSTGRES_DB_HOST=shared-postgres
      - leaderboardstat_POSTGRES_DB_USER=leaderboardstat_user
      - leaderboardstat_POSTGRES_DB_PASSWORD=leaderboardstat_pass
      - leaderboardstat_POSTGRES_DB_NAME=leaderboardstat_db
      - leaderboardstat_POSTGRES_DB_PORT=5432
      - leaderboardstat_REDIS_HOST=shared-redis
      - leaderboardstat_NATS_URL=nats://shared-nats:4222
    entrypoint: [ "air", "-c", "/app/.air/.air.leaderboardstat.toml" ]
networks:
  rankr-shared-development-network:
    external: true
