services:
  leaderboardstat-app:
    build:
      context: ../../.. # Build from the project root
      dockerfile: ./deploy/leaderboardstat/development/Dockerfile
    container_name: leaderboardstat-app
    volumes:
      - ./config.yml:/app/config.yml # Mount the config file
    ports:
      - "8080:8081" # HTTP port
      - "8090:8091" # gRPC port
    networks:
      - rankr-shared-development-network
    environment:
      - CONFIG_PATH=/app/config.yml
      - leaderboardstat_POSTGRES_DB_HOST=shared-postgres
      - leaderboardstat_REDIS_HOST=shared-redis
      - leaderboardstat_NATS_URL=nats://shared-nats:4223
    command: [ "/app/main", "serve", "--migrate-up" ]

networks:
  rankr-shared-development-network:
    external: true