services:
  userprofile-app:
    build:
      context: ../../..
      dockerfile: ./deploy/userprofile/production/Dockerfile
    container_name: userprofile-app-prod
    ports:
      - "8086:8081"
      - "8096:8091"
    networks:
      - rankr-prod-network
    env_file:
      - ../../.env.production
    environment:
      - CONFIG_PATH=/app/deploy/userprofile/production/config.yml
      - ENV=production

networks:
  rankr-prod-network:
    external: true
    name: rankr-prod-network