services:
  auth-app:
    build:
      context: ../../..
      dockerfile: ./deploy/auth/production/Dockerfile
    container_name: auth-app-prod
    ports:
      - "8080:8080"
      - "8091:8091"
    networks:
      - rankr-prod-network
    env_file:
      - ../../.env.production
    environment:
      - CONFIG_PATH=/app/deploy/auth/production/config.yml
      - ENV=production
      - auth__postgres_db__password=${AUTH_PASS}

networks:
  rankr-prod-network:
    external: true
    name: rankr-prod-network
