services:
  leaderboardscoring-app:
    build:
      context: ../../..
      dockerfile: ./deploy/leaderboardscoring/production/Dockerfile
    container_name: leaderboardscoring-app-prod
    ports:
      - "8080:8081"
      - "8090:8070"
    expose:
      - "8070"
    networks:
      - rankr-shared-development-network
    env_file:
      - ./.env.production
    environment:
      - CONFIG_PATH=/app/deploy/leaderboardscoring/production/config.yml
      - ENV=production

networks:
  rankr-shared-development-network:
    external: true
    name: rankr-shared-development-network