services:
  leaderboardscoring-app:
    build:
      context: ../../..
      dockerfile: ./deploy/leaderboardscoring/production/Dockerfile
    container_name: leaderboardscoring-app-prod
    ports:
      - "8083:8081"
      - "8070:8070"
    expose:
      - "8070"
    networks:
      - rankr-prod-network
    env_file:
      - ../../.env.production
    environment:
      - CONFIG_PATH=/app/deploy/leaderboardscoring/production/config.yml
      - ENV=production
      - LEADERBOARDSCORING_POSTGRES_DB__PASSWORD=${LEADERBOARDSCORING_PASS}

networks:
  rankr-prod-network:
    external: true
    name: rankr-prod-network