services:
  project-app:
    build:
      context: ../../..
      dockerfile: ./deploy/project/production/Dockerfile
    container_name: project-app-prod
    ports:
      - "8084:8084"
      - "8094:8094"
    networks:
      - rankr-prod-network
    env_file:
      - ../../.env.production
    environment:
      - CONFIG_PATH=/app/deploy/project/production/config.yml
      - ENV=production
      - PROJECT__POSTGRES_DB__PASSWORD=${PROJECT_PASS}

networks:
  rankr-prod-network:
    external: true
    name: rankr-prod-network