postgres_db:
  driver: postgres
  host: localhost
  port: 5439
  user: contributor_user
  password: change_me_contributor
  db_name: contributor_db
  ssl_mode: disable

path_of_migration: ./contributorapp/repository/migrations