services:
  notification-app:
    build:
      context: ../../.. # Build from the project root
      dockerfile: ./deploy/notification/development/Dockerfile
    container_name: notification-app
    volumes:
      - ./config.yml:/app/config.yml # Mount the config file
    ports:
      - "8089:8081" # HTTP port
      - "8099:8091" # gRPC port
    networks:
      - rankr-shared-development-network
    environment:
      - CONFIG_PATH=/app/config.yml
      - notification_POSTGRES_DB_HOST=shared-postgres
      - notification_POSTGRES_DB_USER=notification_user
      - notification_POSTGRES_DB_PASSWORD=notification_pass
      - notification_POSTGRES_DB_NAME=notification_db
      - notification_POSTGRES_DB_PORT=5432
      - notification_REDIS_HOST=shared-redis
      - notification_NATS_URL=nats://shared-nats:4222
    command: [ "/app/main", "serve" ]
networks:
  rankr-shared-development-network:
    external: true
