services:
  notification-app:
    build:
      context: ../../.. # Build from the project root
      dockerfile: ./deploy/notification/development/Dockerfile
    container_name: notification-app
    volumes:
      - ../../..:/app
    networks:
      - rankr-shared-development-network
    environment:
      - CONFIG_PATH=/app/deploy/notification/development/config.yml
      - notification_POSTGRES_DB_HOST=shared-postgres
      - notification_POSTGRES_DB_USER=notification_user
      - notification_POSTGRES_DB_PASSWORD=change_me_notification
      - notification_POSTGRES_DB_NAME=notification_db
      - notification_POSTGRES_DB_PORT=5432
      - notification_REDIS_HOST=shared-redis
      - notification_NATS_URL=nats://shared-nats:4222
    entrypoint: [ "air", "-c", "/app/.air/.air.notification.toml" ]
networks:
  rankr-shared-development-network:
    external: true
